/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/renderer/index.html",
    "./src/renderer/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    // Calendar holiday colors
    'bg-red-500/30',
    'text-red-800',
    'dark:text-red-200',
    'border-red-500/50',
    'bg-blue-500/30',
    'text-blue-800',
    'dark:text-blue-200',
    'border-blue-500/50',
    // Calendar background highlights
    'bg-amber-100/60',
    'dark:bg-amber-900/30',
    'bg-blue-100/60',
    'dark:bg-blue-900/30',
    'text-amber-800',
    'dark:text-amber-200',
    // Event colors
    'bg-green-500/30',
    'text-green-800',
    'dark:text-green-200',
    'border-green-500/50',
    'bg-yellow-500/30',
    'text-yellow-800',
    'dark:text-yellow-200',
    'border-yellow-500/50',
    'bg-purple-500/30',
    'text-purple-800',
    'dark:text-purple-200',
    'border-purple-500/50',
    'bg-orange-500/30',
    'text-orange-800',
    'dark:text-orange-200',
    'border-orange-500/50',
    'bg-pink-500/30',
    'text-pink-800',
    'dark:text-pink-200',
    'border-pink-500/50',
    'bg-cyan-500/30',
    'text-cyan-800',
    'dark:text-cyan-200',
    'border-cyan-500/50',
    'bg-gray-500/30',
    'text-gray-800',
    'dark:text-gray-200',
    'border-gray-500/50',
    'bg-indigo-500/30',
    'text-indigo-800',
    'dark:text-indigo-200',
    'border-indigo-500/50',
  ],
  theme: {
    extend: {
      colors: {
        // CSS Variables will be used for theming
        // These are fallback values
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        primary: 'var(--color-primary)',
        'primary-foreground': 'var(--color-primary-foreground)',
        secondary: 'var(--color-secondary)',
        'secondary-foreground': 'var(--color-secondary-foreground)',
        accent: 'var(--color-accent)',
        'accent-foreground': 'var(--color-accent-foreground)',
        muted: 'var(--color-muted)',
        'muted-foreground': 'var(--color-muted-foreground)',
        border: 'var(--color-border)',
        input: 'var(--color-input)',
        'input-foreground': 'var(--color-input-foreground)',
        ring: 'var(--color-ring)',
        error: 'var(--color-error)',
        'error-foreground': 'var(--color-error-foreground)',
        success: 'var(--color-success)',
        'success-foreground': 'var(--color-success-foreground)',
        warning: 'var(--color-warning)',
        'warning-foreground': 'var(--color-warning-foreground)',
        info: 'var(--color-info)',
        'info-foreground': 'var(--color-info-foreground)',
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}

